---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: hostlogs
        __path__: /var/log/*.log

  - job_name: system_web
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx
        __path__: /var/log/nginx/*.log

  - job_name: system_gz
    decompression:
      enabled: true
      format: gz
    static_configs:
    - targets:
        - localhost
      labels:
        job: gzlogs
        __path__: /var/log/**.gz
