version: "3.8"
services:
  ntopg:
    image: ntop/ntopng:stable
    network_mode: "host"
    command: ["--community", "-i", "enp195s0","-w","127.0.0.1:8080"]

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:4242:8080
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      DOZZLE_USERNAME: lemmystats
      DOZZLE_PASSWORD: lemmystats
